
ids: ["SRR10053378"]
runID: 'placeholder'
runDIR: '/mnt/illumina/23XXXX_*'

kraken_db: "/mnt/illumina/development/kraken/database/k2_pluspf_20220607/"


  #trimming:
  #  activate: False
  #
  #params:
  #  cutadapt-pe: "--minimum-length 1 -q 20"
  #  cutadapt-se: ""
  #  star: "--outSAMtype BAM SortedByCoordinate"
  #    # --outSAMtype BAM Unsorted"
