# Files
adapters: "/home/schimar/bio/bbmap/resources/adapters.fa"
#reffa: "/home/schimar/bio/ref/gcf_000001405.25_hg19/cds_from_genomic.fna"
#bed: "/home/schimar/bio/ref/gcf_000001405.25_hg19/GCF_000001405.25_GRCh37.p13_genomic.bed"
#gtf: "/home/schimar/bio/ref/GCF_000001405.25_GRCh37.p13_genomic.gtf"

samples: "../config/samples.tsv"

units: "../config/units.tsv"

  #fqDir: "/mnt/illumina/230209_A01272_0035_BHTVFGDRX2/Fastq"

kraken_db: "/mnt/illumina/development/kraken/database/k2_pluspf_20220607/"

  # MHGuide wants you to use 37, check this!
ref:
  # Ensembl species name
  species: Homo_sapiens
  # Ensembl release (make sure to take one where snpeff data is available, check 'snpEff databases' output)
  release: 108    
          #100
  # Genome build
  build: GRCh38

trimming:
  activate: False

params:
  cutadapt-pe: "--minimum-length 1 -q 20"
  cutadapt-se: ""
  star: "--outSAMtype BAM SortedByCoordinate"
    # --outSAMtype BAM Unsorted"
